name: Build pages from CSV

on:
  push:
    paths:
      - 'data/pages.csv'
      - 'scripts/**'
      - 'templates/**'
      - '.github/workflows/build_pages.yml'
  workflow_dispatch:
    inputs:
      csv_path:
        description: Path to CSV (utf-8)
        required: false
        default: data/pages.csv
      out_dir:
        description: Output root
        required: false
        default: docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate pages
        env:
          SITE_BASE: https://gorod-legends.ru
          BOT_URL: https://t.me/luciddreams?start=_tgr_ChFKPawxOGRi
        run: |
          python3 scripts/generate_chat_pages.py \
            --csv "${{ github.event.inputs.csv_path || 'data/pages.csv' }}" \
            --template templates/luna_advanced.html \
            --out "${{ github.event.inputs.out_dir || 'docs' }}"

      - name: Commit changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || git commit -m "Build pages from CSV"
          git push
