name: Build feeds
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "17 2 * * *"  # раз в сутки
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.x" }
      - run: python3 scripts/generate_feeds.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update sitemap & rss"
          branch: main
